Pull request from development to master
trungdinh-novobi/purchase_order_enhancement pull request #1
Opened 2022-07-22 04:51 UTC by trungdinh-novobi

2022-07-22 04:52 UTC, phatdo-novobi commented
You should rename your pull request first!

2022-07-22 05:01 UTC, phatdo-novobi requested changes

2022-07-22 05:01 UTC, phatdo-novobi commented on models/purchase_order.py
> +                record.active = False
Add a new setting to **_Purchase > Configurations > Settings_** for `lifespan` and use it to search old orders here
Also, replace `"|", ("state", "=", "done"), ("state", "=", "cancel")` by ` ("state", "in", ["done", "cancel"])`

2022-07-22 05:01 UTC, phatdo-novobi commented on static/src/js/us_phone_widget.js
> +      }
Why don't we define this function inside the USPhoneNumber class?

2022-07-26 09:11 UTC, phatdo-novobi requested changes

2022-07-26 09:11 UTC, phatdo-novobi commented on controllers/main.py
> +                        "message": "Method '" + params.get("method") + "' are not supported"
replace `are not supported` by `is not supported `

2022-07-26 09:11 UTC, phatdo-novobi commented on controllers/main.py
> +        orders_not_exists = list(set(params.get("orders")) - set(request.env["purchase.order"].sudo().search([]).ids))
Please do not use `search` function with _empty_ domain. You can use:
```
request.env["purchase.order"].sudo().browse(params.get("orders", []))
```
and then try to use `exist` function to perform your check

2022-07-26 09:11 UTC, phatdo-novobi commented on models/purchase_order.py
> +            if (datetime.now() > record.write_date + timedelta(days = int(lifespan))):
Combine `lifespan` into your _search domain_ instead of performing a check here

2022-07-26 09:11 UTC, phatdo-novobi commented on wizard/archive_purchase_orders.py
> +        return {'type': 'ir.actions.client', 'tag': 'reload'}
Remove the `client action` here. Just `return True`

2022-07-27 07:11 UTC, phatdo-novobi requested changes

2022-07-27 07:11 UTC, phatdo-novobi commented on controllers/main.py
> +            request.env["purchase.order"].sudo().browse(params.get("orders")).action_archive_purchase_orders(True)
You should store the result of `request.env["purchase.order"].sudo().browse(params.get("orders"))` into a variable, for example `purchase_orders = request.env["purchase.order"].sudo().browse(params.get("orders"))`. Later you can reuse that instead of calling `request.env["purchase.order"].sudo().browse(params.get("orders"))` multiple times

2022-07-28 16:30 UTC, yenle-novobi requested changes

2022-07-29 10:24 UTC, trungdinh-novobi commented on controllers/main.py
> +        if params.get("method") == None or params.get("orders") == None:
Thanks for your advice. But are you wrong? I think it must be `if not params.get("method", False) or not params.get("orders", False):` .

2022-11-16 08:37 UTC, closed without merging